import Head from 'next/head';
import algoliasearch from 'algoliasearch/lite';
import {
  InstantSearch,
  Hits,
  SearchBox,
  Configure,
} from 'react-instantsearch-dom';
import Navbar from './components/Navbar';
import Movie from './components/Movie';

const searchClient = algoliasearch(
  'PDYVSJO4U8',
  '69a249f8602f8c7d42fb1a00dba7b92f'
);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Trakt TV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InstantSearch indexName="Movie" searchClient={searchClient}>
        <header>
          <SearchBox />
        </header>
        <main className="mx-auto">
          <Hits hitComponent={Movie} />
          <Configure hitsPerPage={16} />
        </main>
      </InstantSearch>
    </div>
  );
}
